manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/lukaslukasm/zmk-builder.git
  projects:
    - name: zmk-builder
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
